name: iOS_bundle_id
description: Get the bundle id of an iOS AppStore app.
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flappy_search_bar: ^1.7.2
  http: ^0.12.0+4
  provider: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
